plugins {
    id 'java'
    id 'groovy'
}

sourceSets {
    externalTest {
        groovy.srcDir file('src/externalTest/groovy')
        resources.srcDir file('src/externalTest/resources')
        compileClasspath += sourceSets.test.output + configurations.testRuntimeClasspath
        runtimeClasspath += output + compileClasspath
    }
}

configurations {
    externalTestImplementation.extendsFrom testImplementation
    externalTestRuntimeOnly.extendsFrom testRuntimeOnly
}

dependencies {
    implementation project(':configurator')

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework:spring-jdbc'
    testImplementation 'org.flywaydb:flyway-core:11.20.3'
    testImplementation "org.spockframework:spock-core:${spockVersion}"
    testImplementation "org.spockframework:spock-spring:${spockVersion}"
    testImplementation "org.testcontainers:testcontainers-spock:${testcontainersVersion}"
    testImplementation "org.testcontainers:testcontainers-jdbc:${testcontainersVersion}"
    testImplementation "org.testcontainers:testcontainers-postgresql:${testcontainersVersion}"
    testImplementation "org.testcontainers:testcontainers-junit-jupiter:${testcontainersVersion}"

    externalTestImplementation 'io.rest-assured:rest-assured:5.5.7'
    testImplementation 'org.apache.groovy:groovy-sql:4.0.33'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    useJUnitPlatform()
    environment 'TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE', '/var/run/docker.sock'
}

tasks.register('externalIntegrationTest', Test) {
    description = 'Runs integration tests against an already running service'
    group = 'verification'
    testClassesDirs = sourceSets.externalTest.output.classesDirs
    classpath = sourceSets.externalTest.runtimeClasspath
    useJUnitPlatform()
    environment 'TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE', '/var/run/docker.sock'
}
