buildscript {
    dependencies {
        classpath 'org.postgresql:postgresql:42.7.13'
    }
}

plugins {
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java'
    id 'jacoco'
    id 'org.openapi.generator' version '7.24.0'
    id 'org.jooq.jooq-codegen-gradle' version "3.21.6"
}

apply from: "$rootDir/configurator/jooq.gradle"
apply from: "$rootDir/configurator/openapi.gradle"

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'io.minio:minio:9.0.3'

    implementation "org.flywaydb:flyway-core:13.1.0"
    runtimeOnly "org.flywaydb:flyway-database-postgresql:13.1.0"
    implementation 'org.postgresql:postgresql:42.7.13'

    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'

    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation "org.spockframework:spock-core:${spockVersion}"
    testImplementation "org.spockframework:spock-spring:${spockVersion}"
    testImplementation 'org.springframework:spring-jdbc'
    testImplementation 'com.h2database:h2'
    testImplementation "com.tngtech.archunit:archunit-junit5:${archUnitVersion}"

    testImplementation "org.testcontainers:testcontainers-postgresql:${testcontainersVersion}"
    testImplementation "org.testcontainers:testcontainers-junit-jupiter:${testcontainersVersion}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named('compileJava') {
    dependsOn tasks.named('openApiGenerate'), tasks.named('jooqCodegen')
}

jacoco {
    toolVersion = '0.8.12'
}

tasks.named('test') {
    finalizedBy tasks.named('jacocoTestReport'), tasks.named('jacocoTestCoverageVerification')
}

tasks.named('jacocoTestReport') {
    dependsOn tasks.named('test')
    reports {
        xml.required = true
        html.required = true
    }

    def excludedCoveragePatterns = [
            '**/build/**',
            '**/common/util/**',
            '**/domain/**',
            '**/domain/entity/jooq/**',
            '**/api/inbounds/rest/dto/**',
            '**/api/inbounds/rest/*Api*',
            '**/api/ApiUtil*',
            '**/infrastructure/persistence/jooq/config/**'
    ]
    classDirectories.setFrom(sourceSets.main.output.asFileTree.matching {
        exclude excludedCoveragePatterns
    })
}

tasks.named('jacocoTestCoverageVerification') {
    dependsOn tasks.named('jacocoTestReport')

    def excludedCoveragePatterns = [
            '**/build/**',
            '**/common/util/**',
            '**/domain/**',
            '**/domain/entity/jooq/**',
            '**/api/inbounds/rest/dto/**',
            '**/api/inbounds/rest/*Api*',
            '**/api/ApiUtil*',
            '**/infrastructure/persistence/jooq/config/**'
    ]
    classDirectories.setFrom(sourceSets.main.output.asFileTree.matching {
        exclude excludedCoveragePatterns
    })

    violationRules {
        rule {
            limit {
                minimum = 0.90
            }
        }
    }
}
